version: '3'
services:
  watch_zeing_official:
    build:
      context: .
      dockerfile: ./eing_script/watch_docker/Dockerfile
    environment:
      - IG_USERNAME= zeing_official
      - IG_PASSWORD= ${IG_PASSWORD}
  like_zeing_official:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - IG_USERNAME= zeing_official
      - IG_PASSWORD= ${IG_PASSWORD}
 